--------------------------------------------------------
-- Archivo creado  - lunes-febrero-12-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USUARIOSADEA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."USUARIOSADEA" 
   (	"LOGIN" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"CLIENTE" FLOAT(126), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"FECHAALTA" DATE, 
	"FECHABAJA" DATE, 
	"STATUS" CHAR(1 BYTE), 
	"INTENTOS" FLOAT(126), 
	"FECHAREVOCADO" DATE, 
	"FECHA_VIGENCIA" DATE, 
	"NO_ACCESO" NUMBER(*,0), 
	"APELLIDO_PATERNO" VARCHAR2(50 BYTE), 
	"APELLIDO_MATERNO" VARCHAR2(50 BYTE), 
	"AREA" NUMBER(4,0), 
	"FECHAMODIFICACION" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.USUARIOSADEA
SET DEFINE OFF;
Insert into SYSTEM.USUARIOSADEA (LOGIN,PASSWORD,NOMBRE,CLIENTE,EMAIL,FECHAALTA,FECHABAJA,STATUS,INTENTOS,FECHAREVOCADO,FECHA_VIGENCIA,NO_ACCESO,APELLIDO_PATERNO,APELLIDO_MATERNO,AREA,FECHAMODIFICACION) values ('chaps','Y2hhcHM=','jesus',1,'jesus@jesus',to_date('22/07/94','DD/MM/RR'),to_date('11/02/24','DD/MM/RR'),'A',0,to_date('11/02/24','DD/MM/RR'),to_date('29/02/24','DD/MM/RR'),1,'chapulin','chapulin',1,to_date('12/02/24','DD/MM/RR'));
Insert into SYSTEM.USUARIOSADEA (LOGIN,PASSWORD,NOMBRE,CLIENTE,EMAIL,FECHAALTA,FECHABAJA,STATUS,INTENTOS,FECHAREVOCADO,FECHA_VIGENCIA,NO_ACCESO,APELLIDO_PATERNO,APELLIDO_MATERNO,AREA,FECHAMODIFICACION) values ('brendaBec','YnJlbmRh','brenda',2,'brenda@brenda',to_date('12/02/24','DD/MM/RR'),null,'A',0,null,to_date('29/02/24','DD/MM/RR'),1,'becerril','becerril',1,to_date('12/02/24','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index SYS_C009742
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C009742" ON "SYSTEM"."USUARIOSADEA" ("LOGIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USUARIOSADEA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."USUARIOSADEA" ADD PRIMARY KEY ("LOGIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."USUARIOSADEA" MODIFY ("FECHAMODIFICACION" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USUARIOSADEA" MODIFY ("INTENTOS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USUARIOSADEA" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USUARIOSADEA" MODIFY ("FECHAALTA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USUARIOSADEA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USUARIOSADEA" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."USUARIOSADEA" MODIFY ("LOGIN" NOT NULL ENABLE);
